name: Setup # The name of the reusable action.
description: Setup for project workflows

runs:
 using: composite

steps:
    - run: python -m pip install --user pipx
      shell: bash

    - run: pipx install poetry
      shell: bash
    
    - uses: actions/setup-python@v5
      with:
        python-version: '>=3.13'
        cache: poetry
